# Generated by Django 2.1.12 on 2022-11-11 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.IntegerField()),
                ('updated_at', models.IntegerField()),
                ('format_created_at', models.DateTimeField(auto_now=True)),
                ('format_updated_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('kind', models.SmallIntegerField(choices=[(0, 'foods'), (1, 'cloths'), (2, 'using')])),
                ('stock', models.IntegerField(default=0)),
                ('introduce', models.CharField(max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'goods',
                'verbose_name_plural': 'goods',
                'db_table': 'goods',
            },
        ),
    ]
