# Generated by Django 2.1.12 on 2022-11-10 09:35

import apiview.model
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, null=True)),
                ('last_name', models.CharField(max_length=200)),
                ('gender', models.SmallIntegerField(choices=[(0, 'FEMALE'), (1, 'MALE'), (2, 'LADYBOY')])),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(default='123456', max_length=200)),
            ],
            options={
                'verbose_name': 'users',
                'verbose_name_plural': 'users',
                'db_table': 'users',
            },
            bases=(models.Model, apiview.model.ModelFieldChangeMixin),
        ),
    ]
